programa: blind-search.cpp
	gcc -std=c++11 -o blind-search blind-search.cpp -lstdc++
	./blind-search
	# cat input.in | ./blind-search > output.out
	# cat input.in | ./blind-search

clean:
	rm blind-search